/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface authUser {
  password: string;
  username: string;
}

export interface base {
  body?: {
    password: string;
    username: string;
  } | object;
  query?: {
    username?: string;
  };
  user?: {
    permissions?: any;
    username: string;
  };
}

export type body = {
  password: string;
  username: string;
} | object;

export type jwtToken = string;

export interface query {
  username?: string;
}

export interface user {
  permissions?: any;
  username: string;
}
