/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface addPermission {
  body: {
    permission: any;
  };
  query: {
    permissionPath?: string[];
    username?: string;
  };
  user: {
    permissions?: any;
    username: string;
  };
}

export interface getPermission {
  body?: {
    password: string;
    username: string;
  } | object;
  query: {
    username?: string;
  };
  user?: {
    permissions?: any;
    username: string;
  };
}

export interface login {
  body?: {
    password: string;
    username: string;
  } | string;
  query?: undefined;
  user?: undefined;
}

export interface logout {
  body?: undefined;
  query?: undefined;
  user: {
    permissions?: any;
    username: string;
  };
}

export interface register {
  body: {
    password: string;
    username: string;
  };
  query?: undefined;
  user?: undefined;
}

export interface removePermission {
  body?: {
    password: string;
    username: string;
  } | object;
  query: {
    permissionPath: string[];
    username?: string;
  };
  user: {
    permissions?: any;
    username: string;
  };
}
