/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface base {
  body?: any;
  query?: any;
}

export interface record {
  hash?: string;
  status?: 'sended' | 'pending' | 'error';
}

export interface recordRequired {
  hash: string;
  status: 'sended' | 'pending' | 'error';
}
