/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface createRecord {
  body: {
    hash: string;
    status: 'sended' | 'pending' | 'error';
  };
  query?: any;
}

export interface deleteRecord {
  body?: any;
  query: {
    hash: string;
  };
}

export interface getRecord {
  body?: any;
  query: {
    hash: string;
  };
}

export interface updateRecord {
  body: {
    hash?: string;
    status?: 'sended' | 'pending' | 'error';
  };
  query: {
    hash: string;
  };
}
