/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface createRecord {
  hash: string;
  status: 'sended' | 'pending' | 'error';
}

export type deleteRecord = boolean;

export interface getRecord {
  hash: string;
  status: 'sended' | 'pending' | 'error';
}

export type updateRecord = boolean;
