/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface createRecord {
  hash: string;
  optInId: string;
  userId: string;
  wallet: string;
}

export type deleteRecord = boolean;

export interface getRecord {
  hash: string;
  optInId: string;
  userId: string;
  wallet: string;
}

export type getRecords = {
  hash: string;
  optInId: string;
  userId: string;
  wallet: string;
}[];

export type updateRecord = boolean;
